import json

path = r"c:\Users\yusuke\programs\pythoncorse1\notebooks\intro_to_programming\exercise-arithmetic-and-variables.ipynb"

with open(path, "r", encoding="utf-8") as f:
    nb = json.load(f)

translations = {
    "**This notebook is an exercise in the [Intro to Programming](https://www.kaggle.com/learn/intro-to-programming) course.  You can reference the tutorial at [this link](https://www.kaggle.com/alexisbcook/arithmetic-and-variables).**\n\n---\n": "**このノートブックは [プログラミング入門](https://www.kaggle.com/learn/intro-to-programming) コースの演習です。チュートリアルは [こちらのリンク](https://www.kaggle.com/alexisbcook/arithmetic-and-variables) から参照できます。**\n\n---\n",
    "This exercise will get you started with running your own code.  \n\n# Set up the notebook\n\nTo begin, run the code in the next cell.\n- Begin by clicking inside the code cell.  \n- Click on the triangle (in the shape of a \"Play button\") that appears to the left of the code cell.\n- If your code was run sucessfully, you will see `Setup Complete` as output below the cell.\n\nInstead of clicking on the triangle, you can also run code by pressing Shift + Enter on your keyboard.  Try this now!  Nothing bad will happen if you run the code more than once.": "この演習では、自分でコードを実行する第一歩を踏み出します。\n\n# ノートブックのセットアップ\n\nまずは、これから新しく追加するセルとその次のセルのコードを実行してください。\n- コードセルの中をクリックして選択します。\n- セルの左側に表示される三角形（「再生ボタン」の形）をクリックします。\n- コードが正常に実行されると、セルの下に `Setup Complete`（セットアップ完了）と表示されます。\n\n三角形をクリックする代わりに、キーボードの Shift + Enter を押してコードを実行することもできます。今すぐ試してみましょう！コードを複数回実行しても何も問題は起こりません。",
    "The code above sets up the notebook so that it can check your answers in this exercise.  You should never modify this code.  (Otherwise, the notebook won't be able to verify that you have successfully completed the exercise.)\n\nAfter finishing all of the questions below, you'll see the exercise marked as complete on the [course page](http://www.kaggle.com/learn/intro-to-programming).  Once you complete all of the lessons, you'll get a course completion certificate!\n\n# Question 1\n\nNext, you will run some code from the tutorial, so you can see how it works for yourself.  Run the next code cell without changes.": "上のコードは、この演習であなたの解答をチェックするためのシステムをセットアップするものです。このコードは絶対に変更しないでください。（変更すると、演習を正しく完了したかどうかの確認ができなくなります。）\n\n以下のすべての質問に答えると、[コースページ](http://www.kaggle.com/learn/intro-to-programming)で演習が完了としてマークされます。すべてのレッスンを完了すると、修了証明書がもらえます！\n\n# 問題 1\n\n次に、チュートリアルにあったコードを実行して、どのように動くかをご自身で確かめます。次のコードセルを変更せずに実行してください。",
    "You just ran code to print `Hello world!`, which you should see in the output above.\n\nThe second line of code (`q1.check()`) checks your answer.  You should never modify this checking code; if you remove it, you won't get credit for completing the problem.\n\n# Question 2\n\nNow, you will print another message of your choosing.  To do this, change `print(\"Your message here!\")` to use a different message.  For instance, you might like to change it to something like:\n- `print(\"Good morning!\")`\n- `print(\"I am learning how to code :D\")`\n\nOr, you might like to see what happens if you write something like `print(\"3+4\")`.  Does it return 7, or does it just think of `\"3+4\"` as just another message?\n\nMake sure that your message is enclosed in quotation marks (`\"`), and the message itself does not use quotation marks. For instance, this will throw an error: `print(\"She said \"great job\" and gave me a high-five!\")` because the message contains quotation marks.  If you decide to take the Python course after completing this course, you will learn more about how to avoid this error in [Lesson 6](https://www.kaggle.com/colinmorris/strings-and-dictionaries).\n\nFeel free to try out multiple messages!": "あなたは今、`Hello, world!` と出力するコードを実行しました。上の出力結果にその文字が表示されているはずです。\n\n2行目のコード (`q1.check()`) はあなたの解答をチェックします。この確認用のコードは絶対に変更しないでください；これを削除してしまうと、問題のクリア判定がもらえません。\n\n# 問題 2\n\n次は、自分の好きなメッセージを出力してみましょう。そのためには、`print(\"Your message here!\")` の部分を別のメッセージに変更します。例えば、次のように書くことができます:\n- `print(\"Good morning!\")`\n- `print(\"I am learning how to code :D\")`\n\nまた、`print(\"3+4\")` と書いたらどうなるか試してみるのも良いでしょう。7が返ってくるでしょうか、それとも `\"3+4\"` をただのメッセージとして扱うでしょうか？\n\nメッセージは必ず引用符 (`\"`) で囲むこと、そしてメッセージ自体に同じ引用符を使わないように注意してください。例えば、`print(\"She said \"great job\" and gave me a high-five!\")` は、メッセージの中に引用符が含まれているためエラーになります。このコースを終えた後にPythonコースを受講すれば、[レッスン6](https://www.kaggle.com/colinmorris/strings-and-dictionaries)でこのエラーを回避する方法についてさらに詳しく学ぶことができます。\n\n自由にいろいろなメッセージを試してみてください！",
    "# Question 3\n\nAs you learned in the tutorial, a comment in Python has a pound sign (`#`) in front of it, which tells Python to ignore the text after it.\n\nPutting a pound sign in front of a line of code will make Python ignore that code.  For instance, this line would be ignored by Python, and nothing would appear in the output:\n```python\n#print(1+2)\n```\nRemoving the pound sign will make it so that you can run the code again. When we remove the pound sign in front of a line of code, we call this **uncommenting**.\n\nIn this problem, you will uncomment two lines in the code cell below and view the output:\n- Remove the `#` in front of `q3.hint()`.  To avoid errors, do NOT remove the `#` in front of `# Uncomment to view hint`.  \n- Next, remove the `#` in front of `q3.solution()`.\n\nAs in the previous questions, do not change the final line of code that marks your work as completed.": "# 問題 3\n\nチュートリアルで学んだように、Pythonでのコメントは前に記号 (`#`) がついており、これはPythonにそれ以降のテキストを無視するように伝えます。\n\nコード行の前にこの記号を置くと、Pythonはそのコードを無視します。たとえば、次の行はPythonによって無視され、出力には何も表示されません：\n```python\n#print(1+2)\n```\n記号を削除すると、そのコードを再び実行できるようになります。コード行の前の記号を削除することを、**コメントアウトを外す（アンコメント）** と呼びます。\n\nこの問題では、下のコードセルにある2行のコメントを外して出力を見てみます：\n- `q3.hint()` の前にある `#` を削除します。エラーを防ぐため、`# Uncomment to view hint` の前にある `#` は絶対に削除しないでください。\n- 次に、`q3.solution()` の前にある `#` を削除します。\n\nこれまでの問題と同様に、回答完了をマークするための最後のコード行は変更しないでください。",
    "In the next question, and in most of the exercises in this course, you will have the option to uncomment to view hints and solutions.  Once you feel comfortable with uncommenting, continue to the next question.\n": "次の問題や、このコースのほとんどの演習では、コメントを外すことでヒントや解答を見ることができます。コメントを外すことに慣れたら、次の問題に進んでください。\n",
    "# Question 4\n\nIn the tutorial, you defined several variables to calculate the total number of seconds in a year.  Run the next code cell to do the calculation here.": "# 問題 4\n\nチュートリアルでは、1年間の合計秒数を計算するために複数の変数を定義しました。次のコードセルを実行して、ここでその計算を行ってください。",
    "Use the next code cell to:\n- Define a variable `births_per_min` and set it to 250.  (There are on average 250 babies born each minute.)\n- Define a variable `births_per_day` that contains the average number of babies born each day.  (To set the value of this variable, you should use `births_per_min` and some of the variables from the previous code cell.)\n\nRemember you can always get a hint if you need it!": "次のコードセルを使って以下を行います：\n- 変数 `births_per_min` を定義し、250に設定します。（平均して毎分250人の赤ちゃんが生まれるとします。）\n- 毎日生まれる赤ちゃんの平均数を含む変数 `births_per_day` を定義します。（この変数の値を設定するには、`births_per_min` と前のコードセルの変数のいくつかを使用する必要があります。）\n\n必要なときはいつでもヒントを見ることができるのを忘れないでください！",
    "# 🌶️ Question 5\n\n(Questions marked with a 🌶️ will be a little bit more challenging than the others!  Remember you can always get a hint or view the solution.)\n\nThe [Titanic competition](https://www.kaggle.com/c/titanic) is Kaggle's most famous data science competition. In this competition, participants are challenged to build a machine learning model that can predict whether or not passengers survived the Titanic shipwreck, based on information like age, sex, family size, and ticket number.\n\nRun the next code cell without changes to load and preview the titanic data.\n\nDon't worry about the details of the code for now - the end result is just that the all of the titanic data has been loaded in a variable named `titanic_data`.  (In order to learn how to write this code yourself, you can take the [Python course](https://www.kaggle.com/learn/python) and then the [Pandas course](https://www.kaggle.com/learn/pandas).)": "# 🌶️ 問題 5\n\n（🌶️マークが付いた問題は、他の問題よりも少しだけ挑戦的です！いつでもヒントを見たり解答を確認したりできることを忘れないでください。）\n\n[タイタニックコンペティション](https://www.kaggle.com/c/titanic) はKaggleで最も有名なデータサイエンスコンペです。このコンペでは、参加者は年齢、性別、家族の規模、チケット番号などの情報に基づいて、乗客がタイタニック号の難破事故を生き延びたかどうかを予測する機械学習モデルの構築に挑戦します。\n\n次のコードセルを変更せずに実行し、タイタニックのデータを読み込んでプレビューします。\n\n今のところコードの詳細は気にしないでください。最終的な結果は、すべてのタイタニックのデータが `titanic_data` という名前の変数に読み込まれたということだけです。（このコードを自分で書く方法を学ぶには、[Pythonコース](https://www.kaggle.com/learn/python)を受講し、その後に[Pandasコース](https://www.kaggle.com/learn/pandas)を受講すると良いでしょう。）",
    "The data has a different row for each passenger.  \n\nThe next code cell defines and prints the values of three variables:  \n- `total` = total number of passengers who boarded the ship\n- `survived` = number of passengers who survived the shipwreck\n- `minors` = number of passengers under 18 years of age\n\nRun the code cell without changes.  (Don't worry about the details of how these variables are calculated for now.  You can learn more about how to calculate these values in the [Pandas course](https://www.kaggle.com/learn/pandas).)": "データには乗客ごとに異なる行があります。\n\n次のコードセルでは、3つの変数の値を定義して出力します：\n- `total` = 船に乗船した乗客の総数\n- `survived` = 難破を生き延びた乗客の数\n- `minors` = 18歳未満の乗客の数\n\nコードセルを変更せずに実行してください。（今のところ、これらの変数がどのように計算されるかの詳細は気にしないでください。これらの値の計算方法については、[Pandasコース](https://www.kaggle.com/learn/pandas)で詳しく学ぶことができます。）",
    "So, \n- `total = 891` (there were 891 passengers on board the Titanic),\n- `survived = 342` (342 passengers survived), and \n- `minors = 113` (113 passengers were under the age of 18).\n\nIn the code cell below, replace the underlines (`____`) with code to calculate the values for two more variables:\n- `survived_fraction` should be set to the fraction of passengers who survived the Titanic disaster.\n- `minors_fraction` should be the fraction of passengers who were minors (under the age of 18).\n\nFor each variable, your answer should be a number between 0 and 1.  \n\nIf you need a hint or want to view the solution, you can skip to the next code cell and uncomment the appropriate lines of code (`q5.hint()` and `q5.solution()`).": "つまり、\n- `total = 891` (タイタニック号には891人の乗客が乗っていました)\n- `survived = 342` (342人の乗客が生き延びました)\n- `minors = 113` (113人の乗客が18歳未満でした)\n\n下のコードセルで、アンダーライン (`____`) を置き換えてコードを書き、さらに2つの変数の値を計算してください：\n- `survived_fraction` には、タイタニックの事故から生き延びた乗客の割合を設定する必要があります。\n- `minors_fraction` には、未成年（18歳未満）の乗客の割合を設定する必要があります。\n\nそれぞれの変数について、答えは0から1の間の数字になります。\n\nヒントが必要な場合や解答を見たい場合は、次のコードセルに進み、適切なコード行（`q5.hint()` と `q5.solution()`）のコメントを外してください。",
    "# Bonus Exercise\n\nAs an **optional** next step, you're encouraged to make a submission to the Titanic competition.  \n> To do this, follow the instructions in the **[notebook here](https://www.kaggle.com/alexisbcook/titanic-tutorial)**.  \n\nThe notebook is beginner-friendly and does not assume you have any experience with coding.  At the same time, you'll learn how to author your own notebooks on Kaggle, and it gives you a great idea of what you'll be able to do if you continue to learn data science!\n\n# Keep going\n\nCongratulations!  You have just finished the first exercise in the Intro to Programming course!  \n\nYou are now ready to learn how to **[organize your code with functions](https://www.kaggle.com/alexisbcook/functions)**.": "# ボーナス演習\n\n**オプション**の次のステップとして、タイタニックコンペティションへの提出を行ってみることをお勧めします。\n> これを行うには、**[こちらのノートブック](https://www.kaggle.com/alexisbcook/titanic-tutorial)** の指示に従ってください。\n\nこのノートブックは初心者にも優しく、コーディングの経験があることを前提としていません。と同時に、Kaggleで自分自身のノートブックを作成する方法を学べるため、データサイエンスの学習を続けた場合に何ができるようになるかという素晴らしいイメージを掴むことができます！\n\n# 次に進む\n\nおめでとうございます！あなたは今、プログラミング入門コースでの最初の演習を終えました！\n\nこれで、**[関数を使ってコードを整理する方法](https://www.kaggle.com/alexisbcook/functions)** を学ぶ準備が整いました。",
    "---\n\n\n\n\n*Have questions or comments? Visit the [course discussion forum](https://www.kaggle.com/learn/intro-to-programming/discussion) to chat with other learners.*": "---\n\n*質問やコメントがありますか？[コース ディスカッション フォーラム](https://www.kaggle.com/learn/intro-to-programming/discussion)を訪問して、他の学習者とチャットをしてみましょう。*"
}

for cell in nb["cells"]:
    if cell["cell_type"] == "markdown":
        src = "".join(cell["source"])
        if src in translations:
            cell["source"] = [translations[src]]

# ここで json.dump() を `separators=(',', ':')` で出力することで、
# Kaggle APIからダウンロードした「改行なし・インデントなし」のMinifiedな状態を完全維持します。
with open(path, "w", encoding="utf-8") as f:
    json.dump(nb, f, ensure_ascii=False, separators=(',', ':'))

print("Markdown translation completed successfully.")
