import json

path_func = r"/Users/yusuke/programs/pythoncorse1/notebooks/intro_to_programming/functions.ipynb"
path_ex = r"/Users/yusuke/programs/pythoncorse1/notebooks/intro_to_programming/exercise-functions.ipynb"

translations_func = {
    "# Introduction\n\nIn this lesson, you will learn how to organize your code with functions.  A **function** is a block of code designed to perform a specific task.  As you'll see, functions will let you do roughly the same calculation multiple times without duplicating any code.  \n\n# Intro to functions: a simple example\n\nWe begin with a simple example of a function.  The `add_three()` function below accepts any number, adds three to it, and then returns the result.":
    "# 入門\n\nこのレッスンでは、関数（Functions）を使ってコードを整理する方法を学びます。**関数**は、特定のタスクを実行するために設計されたコードのブロックです。後でわかるように、関数を使うと同じような計算を複数回おこなう際にコードを複製せずに済みます。\n\n# 関数の基礎：簡単な例\n\nまずは簡単な関数の例から始めましょう。以下の `add_three()` 関数は、任意の数字を受け取り、それに3を足して結果を返します。",
    
    "Every function is composed of two pieces: a **header** and **body**.\n\n![](https://storage.googleapis.com/kaggle-media/learn/images/gu0AWhK.png)\n\n## Header\nThe function **header** defines the name of the function and its argument(s).  \n- Every function header begins with `def`, which tells Python that we are about to define a function.\n- In the example, the function name is `add_three`.  \n- In the example, the argument is `input_var`.  The **argument** is the name of the variable that will be used as input to the function. It is always enclosed in parentheses that apppear immediately after the name of the function.  (_Note that a function can also have no arguments, or it can have multiple arguments.  You'll see some examples of this later in the lesson._)  \n- For every function, the parentheses enclosing the function argument(s) must be followed by a colon `:`.\n \n## Body\nThe function **body** specifies the work that the function does.\n- Every line of code in the function body must be indented exactly four spaces.  You can do this by pushing the space bar four times, or by hitting the \"Tab\" button once on your keyboard.  (_As you learn more about Python, you may need to indent your code by more than four spaces, but you'll learn more about that later in this course._)\n- The function does its work by running all of the indented lines from top to bottom.  \n    - It takes the argument as input, which in the example is `input_var`.  \n    - The function creates a new variable `output_var` with the calculation `output_var = input_var + 3`.\n    - Then, the final line of code, called the **return statement**, just returns the value in `output_var` as the function's output.\n  \nThe code cell above just defines the function, but does not run it.  The details of the function body will make more sense after the next code cell, when we actually run the function.\n\n# How to run (or \"call\") a function\n \nWhen we run a function, it can also be referred to as \"calling\" the function.\n\nIn the code cell below, we run the function with `10` as the input value.  We define a new variable `new_number` which is set to the output of the function.":
    "すべての関数は、**ヘッダー（header）**と**ボディ（body）**の2つの部分で構成されています。\n\n![](https://storage.googleapis.com/kaggle-media/learn/images/gu0AWhK.png)\n\n## ヘッダー\n関数の**ヘッダー**は、関数の名前とその引数（argument）を定義します。\n- すべての関数ヘッダーは `def` から始まります。これは、これから関数を定義することをPythonに伝えます。\n- 例では、関数の名前は `add_three` です。\n- 例では、引数は `input_var` です。**引数**とは、関数への入力として使用される変数の名前です。引数は常に関数名のすぐ後ろにある括弧で囲まれます。（*注：関数には引数がない場合もあれば、複数の引数がある場合もあります。このレッスンの後半でいくつか例を見ていきます。*）\n- すべての関数において、関数の引数を囲む括弧の後にはコロン `:` を付ける必要があります。\n\n## ボディ\n関数の**ボディ**は、関数が実行する作業を指定します。\n- 関数のボディにあるすべてのコード行は、正確に4つのスペースでインデント（字下げ）されている必要があります。スペースキーを4回押すか、キーボードの「Tab」ボタンを1回押すことで行うことができます。（*Pythonについてさらに学ぶにつれて、4つ以上のスペースでインデントする必要が出てくるかもしれませんが、それについてはこのコースの後半で詳しく学びます。*）\n- 関数は、インデントされたすべての行を上から下へ実行することでその作業を行います。\n    - 例にある `input_var` のように、引数を入力として受け取ります。\n    - 関数は、計算 `output_var = input_var + 3` を用いて、新しい変数 `output_var` を作成します。\n    - そして最後のコード行である**return（戻り値）文**が、関数の出力として `output_var` の値を単に返します。\n\n上のコードセルは関数を定義しているだけであり、実行はしていません。関数のボディの詳細は、実際に関数を実行する次のコードセルの後にさらに意味がわかるようになるでしょう。\n\n# 関数の実行（呼び出し）方法\n\n関数を実行することを、関数を「呼び出す（calling）」とも表現します。\n\n下のコードセルでは、入力値として `10` を指定して関数を実行します。そして、関数の出力に設定される新しい変数 `new_number` を定義しています。",
    
    "![](https://storage.googleapis.com/kaggle-media/learn/images/hlUbxQE.png)\n\nIn more detail,\n- `add_three(10)` is the value that we get as output when we supply `10` as the value for `input_var` and call the `add_three()` function.  When the function runs, it runs all of the code in its body, from top to bottom:\n  - It first calculates `output_var = input_var + 3`, which sets `output_var = 13`.  \n  - The final line of code is the return statement, which returns the value of `output_var`, which is `13`.\n- By setting `new_number = add_three(10)`, we set `new_number = 13`. \n\n**Note**: When we casually refer to the `add_three()` function in this tutorial, we use empty closing parentheses after the function name.  This is consistent with how people generally write explanations of Python code, and the empty parentheses just make it clear that we are referring to a function, as opposed to a variable or another Python object.  These parentheses should always be empty, even if the function has arguments.\n\n# Naming functions\n\nIn the example above, the name of the function was selected for you.  When naming your own functions, you should use only lowercase letters, with words separated by underscores instead of spaces.\n\nNaming functions will feel natural over time, and it is normal for it to feel uncomfortable at first.  The best way to learn is by viewing a lot of Python code.":
    "![](https://storage.googleapis.com/kaggle-media/learn/images/hlUbxQE.png)\n\n詳細については以下の通りです：\n- `add_three(10)` は、`input_var` の値として `10` を提供し、`add_three()` 関数を呼び出したときに出力として得られる値です。関数が実行されると、そのボディ内のすべてのコードが上から下へと実行されます：\n  - まず `output_var = input_var + 3` を計算し、`output_var = 13` に設定されます。\n  - 最後のコード行がreturn文で、`output_var` の値である `13` を返します。\n- `new_number = add_three(10)` と設定することで、`new_number = 13` と設定したことになります。\n\n**注**: このチュートリアルで何気なく `add_three()` 関数に言及するとき、関数名の後に空の閉じ括弧を使用しています。これは、人々が一般的にPythonコードの説明を書く方法と一致しており、空の括弧は、変数や他のPythonオブジェクトではなく関数を参照していることを明確にするためのものです。関数に引数がある場合でも、これらの括弧は常に空であるべきです。\n\n# 関数の命名\n\n上の例では、関数の名前はあらかじめ選ばれていました。自分で関数に名前を付けるときは、小文字のみを使用し、スペースの代わりにアンダースコアで単語を区切るようにしてください。\n\n関数の命名は時間が経てば自然に感じられるようになりますし、最初は違和感があるのが普通です。Pythonのコードをたくさん見ることが一番の学習方法です。",
    
    "# A more complex example\n\nNow that you understand the basics, we can move on to an example with a longer calculation.\n\nSay you are helping a friend to calculate their weekly paycheck after taxes. \n- They're in a 12% tax bracket (in other words, 12% of their salary is taken for taxes, and they only take home 88%), and \n- They're paid hourly, at a rate of $15/hour.\n\nThe function below calculates the paycheck based on the number of hours worked.  The function is more complicated than with the first example, because the function has more lines of code and comments.  Similar to the example above, the function has a single argument (`num hours`).  In the function body, we:\n- Use the value for `num_hours` to specify the value for a new variable `pay_pretax`.\n- Use the value of `pay_pretax` to specify the value for a new variable `pay_aftertax`.\n- Return the value of the `pay_aftertax` variable.":
    "# より複雑な例\n\n基本がわかったところで、より長い計算の例に進みましょう。\n\n友人が税引き後の週給を計算するのを手伝っているとします。\n- 友人は12%の税率区分にいます（言い換えれば、給与の12%が税金として引かれ、88%だけを持ち帰ることになります）\n- 友人は時給制で、時給15ドルで支払われます。\n\n以下の関数は、働いた時間数に基づいて給与を計算します。前の例よりもコード行数やコメントが多いため、少し複雑になっています。上の例と同様に、関数には単一の引数（`num_hours`）があります。関数のボディでは：\n- `num_hours` の値を使用して、新しい変数 `pay_pretax` の値を指定します。\n- `pay_pretax` の値を使用して、新しい変数 `pay_aftertax` の値を指定します。\n- `pay_aftertax` 変数の値を返します。",
    
    "We call this function the same way we called the first function.  The next code cell calculates the paycheck, based on working 40 hours.  (After taxes, it is $528.)":
    "この関数は、最初の関数を呼び出したのと同じ方法で呼び出します。次のコードセルは、40時間働いた場合に基づいて給与を計算します。（税引き後で528ドルです。）",
    
    "To quickly calculate pay based on a different number of hours worked, you need to supply the function with a different number.  For instance, say your friend works 32 hours.  (Then, they get $422.40.)":
    "異なる労働時間に基づいて給与を素早く計算するには、関数に異なる数字を提供するだけです。例えば、友人が32時間働いたとします。（すると、422.40ドルになります。）",
    
    "Because you wrote a function, you can calculate pay for different hours without having to rewrite all of the code in the calculations all over again. \n\nFunctions can help you to avoid errors in your code, and you save a lot of time.  In general, when coding, you should aim to write as little as possible, because each time you type out a calculation, it's another opportunity to accidentally introduce a typo or error. \n\n# Variable \"scope\"\n\nVariables defined inside the function body cannot be accessed outside of the function.  For instance, the next code cell errors, because `pay_aftertax` only exists inside the function.":
    "関数を書いたおかげで、計算のコードをすべて書き直すことなく、異なる時間の給与を計算することができます。\n\n関数はコードのエラーを避けるのに役立ち、また多くの時間を節約してくれます。一般的に、コーディングの際はできるだけ書く量を少なくすることを目指すべきです。なぜなら、計算を毎回打ち込むたびに、タイプミスやエラーを誤って持ち込んでしまう可能性があるからです。\n\n# 変数の「スコープ（適用範囲）」\n\n関数のボディ内で定義された変数は、関数の外からはアクセスできません。例えば、次のコードセルは `pay_aftertax` が関数の中にしか存在しないため、エラーになります。",
    
    "You will get the same error if you try to print `pay_pretax` or `num_hours`.  For this reason, if you need any information from a function, you need to make sure that appears in the return statement at the end of the function.\n\nWe refer to a variable's **scope** as the part of the code where it is accessible.  Variables defined _inside a function_ (like `pay_aftertax`) have a local scope of that function only.  However, as you've seen, variables defined _outside all functions_ (like `pay_parttime`) have a global scope and can be accessed anywhere.":
    "`pay_pretax` や `num_hours` を出力しようとした場合も同じエラーになります。このため、関数から何らかの情報が必要な場合は、それが関数の最後にある return文 に含まれていることを確認する必要があります。\n\n変数がアクセスできるコードの領域のことを、変数の**スコープ**と呼びます。関数のボディのように _関数の内部_ で定義された変数（たとえば `pay_aftertax`）は、その関数だけの「ローカルスコープ」を持ちます。しかし、これまでに見てきたように、_すべての関数の外_ で定義された変数（たとえば `pay_parttime`）は「グローバルスコープ」を持ち、どこからでもアクセスすることができます。",
    
    "# Functions with multiple arguments\n\nSo far, you have learned how to define a function with just one argument.  To define a function with multiple arguments, you only need to add more arguments inside the parentheses in the function head and separate them with a comma.\n\nWe do this with the `get_pay_with_more_inputs()` function below, which calculates a weekly paycheck based on three arguments:\n- `num_hours` - number of hours worked in one week\n- `hourly_wage` - the hourly wage (in $/hour)\n- `tax_bracket` - percentage of your salary that is removed for taxes":
    "# 複数の引数を持つ関数\n\nここまで、1つの引数だけを持つ関数を定義する方法を学びました。複数の引数を持つ関数を定義するには、関数のヘッダーにある括弧の中により多くの引数を追加し、それらをカンマで区切るだけです。\n\n以下の `get_pay_with_more_inputs()` 関数を使ってこれを行います。この関数は、次の3つの引数に基づいて週給を計算します：\n- `num_hours` - 1週間に働いた時間数\n- `hourly_wage` - 時給（ドル/時間）\n- `tax_bracket` - 税金として引かれる給与の割合",
    
    "Then, to call the function, you need to provide one value for each input, again separated by a comma.\n\nIn the code cell below, we calculate the pay after taxes for someone who works 40 hours, makes $24/hour, and is in a 22% tax bracket.":
    "そして関数を呼び出すためには、各入力につき１つの値を提供し、またカンマで区切る必要があります。\n\n以下のコードセルでは、40時間働き、時給24ドルで、22%の税率区分の人の税引き後給与を計算します。",
    
    "The following code cell gives the same result as when we ran `get_pay(40)`, because `hourly_wage` is set to 15, and `tax_bracket` is set to 12%, which lines up with how we designed `get_pay`.":
    "次のコードセルは、`get_pay(40)` を実行したときと同じ結果になります。なぜなら `hourly_wage` が15に設定され、`tax_bracket` が12%に設定されており、これは `get_pay` を設計した方法と一致しているからです。",
    
    "Depending on how we plan to use this new function `get_pay_with_more_inputs()`, it can be more useful than the original function `get_pay()`, because it addresses more cases.  Instead of potentially incorrectly assuming the hourly wage and tax bracket, the new function allows the user to specify the correct values.  But, if you're sure the hourly wage and tax bracket won't need to change, the new function is just more complicated than necessary.  In general, when defining functions, you'll need to consider how much flexibility you need, based on your use case. \n\n# Functions with no arguments\n\nNote that it's possible to define function with no arguments, and that don't have a return statement.  The `print_hello()` function in the code cell below is an example.  ":
    "この新しい関数 `get_pay_with_more_inputs()` をどう使用するかにもよりますが、オリジナルの `get_pay()` 関数よりも多くのケースに対応できるため、より有用といえます。新しい関数では、ユーザーが時給と税率を誤って仮定してしまう可能性がある代わりに、正しい値を指定できるようになっています。しかし、もし時給と税率が変わる必要がないことがわかっているのであれば、新しい関数は必要以上に複雑なだけです。一般的に関数を定義する際は、使用ケースに基づいてどれだけの柔軟性が必要かを考慮する必要があります。\n\n# 引数を持たない関数\n\n引数を持たず、return文を持たない関数を定義することも可能であることに注意してください。下のコードセルの `print_hello()` 関数がその一例です。",
    
    "This course is short and meant as an introduction to programming, so we won't cover everything you need to know about functions in this tutorial.  You'll learn even more about functions in [the Python course](http://www.kaggle.com/learn/python).\n\n# Your turn\n\nIt's time to **[write your own functions in Python](https://www.kaggle.com/kernels/fork/25258227)**.":
    "このコースは短く、プログラミング入門として意図されているため、このチュートリアルで関数について知るべきことすべてを網羅するわけではありません。関数については、[Pythonコース](http://www.kaggle.com/learn/python)でさらに詳しく学ぶことになります。\n\n# あなたの番です\n\n**[Pythonで自分自身の関数を書く](https://www.kaggle.com/kernels/fork/25258227)** 時間です。",
    
    "---\n\n\n\n\n*Have questions or comments? Visit the [course discussion forum](https://www.kaggle.com/learn/intro-to-programming/discussion) to chat with other learners.*":
    "---\n\n*質問やコメントがありますか？[コース ディスカッション フォーラム](https://www.kaggle.com/learn/intro-to-programming/discussion)を訪問して、他の学習者とチャットをしてみましょう。*"

}

translations_ex = {
    "**This notebook is an exercise in the [Intro to Programming](https://www.kaggle.com/learn/intro-to-programming) course.  You can reference the tutorial at [this link](https://www.kaggle.com/alexisbcook/functions).**\n\n---\n":
    "**このノートブックは [プログラミング入門](https://www.kaggle.com/learn/intro-to-programming) コースの演習です。チュートリアルは [こちらのリンク](https://www.kaggle.com/alexisbcook/functions) から参照できます。**\n\n---\n",

    "In the tutorial, you learned about functions. In this exercise, you'll write some of your own!\n\n# Set up the notebook\n\nRun the next code cell without changes to set up the notebook.":
    "チュートリアルでは関数について学びました。この演習では、あなた自身で関数を書いていただきます！\n\n# ノートブックのセットアップ\n\n次のコードセルを変更せずに実行して、ノートブックをセットアップしてください。",

    "# Question 1\n\nIn the [House Prices - Advanced Regression Techniques competition](https://www.kaggle.com/c/house-prices-advanced-regression-techniques/overview), you need to use information like the number of bedrooms and bathrooms to predict the price of a house.  Inspired by this competition, you'll write your own function to do this.\n\nIn the next code cell, create a function `get_expected_cost()` that has two arguments:\n- `beds` - number of bedrooms \n- `baths` - number of bathrooms\n\nIt should return the expected cost of a house with that number of bedrooms and bathrooms.  Assume that:\n- the expected cost for a house with 0 bedrooms and 0 bathrooms is `80000`.  \n- each bedroom adds `30000` to the expected cost\n- each bathroom adds `10000` to the expected cost.\n\nFor instance, \n- a house with 1 bedroom and 1 bathroom has an expected cost of `120000`, and \n- a house with 2 bedrooms and 1 bathroom has an expected cost of `150000`.":
    "# 問題 1\n\n[住宅価格 - 高度な回帰テクニックコンペティション](https://www.kaggle.com/c/house-prices-advanced-regression-techniques/overview)では、ベッドルームやバスルームの数などの情報を使用して家の価格を予測する必要があります。このコンペティションに触発されて、同じことをする自分自身の関数を書きます。\n\n次のコードセルで、2つの引数を持つ関数 `get_expected_cost()` を作成します：\n- `beds` - ベッドルームの数\n- `baths` - バスルームの数\n\nこの関数は、その数のベッドルームとバスルームを持つ家の予想価格を返す必要があります。以下を前提とします：\n- ベッドルーム0個、バスルーム0個の家の予想価格は `80000` です。\n- ベッドルームが1つ増えるごとに、予想価格に `30000` が追加されます。\n- バスルームが1つ増えるごとに、予想価格に `10000` が追加されます。\n\n例えば、\n- ベッドルーム1個、バスルーム1個の家の予想価格は `120000` です\n- ベッドルーム2個、バスルーム1個の家の予想価格は `150000` です。",

    "# Question 2\n\nYou are thinking about buying a home and want to get an idea of how much you will spend, based on the number of bedrooms and bathrooms.  You are trying to decide between four different options:\n- Option 1: house with two bedrooms and three bathrooms\n- Option 2: house with three bedrooms and two bathrooms\n- Option 3: house with three bedrooms and three bathrooms\n- Option 4: house with three bedrooms and four bathrooms\n\nUse the `get_expected_cost()` function you defined in question 1 to set `option_1`, `option_2`, `option_3`, and `option_4` to the expected cost of each option.":
    "# 問題 2\n\nあなたは家を買うことを考えていて、ベッドルームとバスルームの数に基づいてどれくらいのお金がかかるのか見当をつけたいと思っています。以下の4つの異なるオプションの間で決めようとしています：\n- オプション 1: 2つのベッドルームと3つのバスルームを持つ家\n- オプション 2: 3つのベッドルームと2つのバスルームを持つ家\n- オプション 3: 3つのベッドルームと3つのバスルームを持つ家\n- オプション 4: 3つのベッドルームと4つのバスルームを持つ家\n\n問題 1 で定義した `get_expected_cost()` 関数を使用して、`option_1`、`option_2`、`option_3`、`option_4` にそれぞれのオプションの予想価格を設定してください。",

    "# Question 3\n\nYou're a home decorator, and you'd like to use Python to streamline some of your work.  Specifically, you're creating a tool that you intend to use to calculate the cost of painting a room.\n\nAs a first step, define a function `get_cost()` that takes as input:\n- `sqft_walls` = total square feet of walls to be painted\n- `sqft_ceiling` = square feet of ceiling to be painted\n- `sqft_per_gallon` = number of square feet that you can cover with one gallon of paint\n- `cost_per_gallon` = cost (in dollars) of one gallon of paint\n\nIt should return the cost (in dollars) of putting one coat of paint on all walls and the ceiling.  Assume you can buy the exact amount of paint that you need, so you can buy partial gallons (e.g., if you need 7.523 gallons, you can buy that exact amount, instead of needing to buy 8 gallons and waste some paint).  Do not round your answer.":
    "# 問題 3\n\nあなたはホームデコレーターで、作業の一部を効率化するためにPythonを使いたいと考えています。具体的には、部屋の塗装にかかる費用を計算するためのツールを作成しようとしています。\n\n最初のステップとして、以下の入力を受け取る関数 `get_cost()` を定義します：\n- `sqft_walls` = 塗装する壁の総面積（平方フィート）\n- `sqft_ceiling` = 塗装する天井の総面積（平方フィート）\n- `sqft_per_gallon` = 1ガロンのペンキで塗装できる面積（平方フィート）\n- `cost_per_gallon` = ペンキ1ガロンあたりのコスト（ドル）\n\nこの関数は、すべての壁と天井に1度の塗装を行うためのコスト（ドル）を返さなければなりません。必要なペンキの正確な量を購入できると仮定し、一部のガロン（例えば、7.523ガロン必要な場合、8ガロン買ってペンキを無駄にする必要はなく、その正確な量を購入できる）を購入できるものとします。回答は四捨五入しないでください。",

    "# Question 4\n\nUse the `get_cost()` function you defined in Question 3 to calculate the cost of applying one coat of paint to a room with:\n- 432 square feet of walls, and\n- 144 square feet of ceiling.\n\nAssume that one gallon of paint covers 400 square feet and costs $15.  As in Question 3, assume you can buy partial gallons of paint.  Do not round your answer.":
    "# 問題 4\n\n問題3で定義した `get_cost()` 関数を使用して、以下のような部屋に1度塗りを行うためのコストを計算してください：\n- 432平方フィートの壁\n- 144平方フィートの天井\n\n1ガロンのペンキは400平方フィートをカバーし、15ドルかかると仮定します。問題3と同様に、ガロンの一部を購入できると仮定します。回答は四捨五入しないでください。",

    "# 🌶️ Question 5\n\nNow say you can no longer buy fractions of a gallon.  (For instance, if you need 4.3 gallons to do a project, then you have to buy 5 gallons of paint.)\n\nWith this new scenario, you will create a new function `get_actual_cost` that uses the same inputs and calculates the cost of your project.\n\nOne function that you'll need to use to do this is `math.ceil()`.  We demonstrate usage of this function in the code cell below.  It takes as a number as input and rounds the number up to the nearest integer.  \n\nRun the next code cell to test this function for yourself.  Feel free to change the value of `test_value` and make sure `math.ceil()` returns the number you expect.":
    "# 🌶️ 問題 5\n\nさて、もはやガロンの一部を購入することができなくなったとしましょう。（例えば、プロジェクトを行うために4.3ガロン必要な場合、5ガロンのペンキを購入する必要があります。）\n\nこの新しいシナリオでは、同じ入力を使用してプロジェクトのコストを計算する新しい関数 `get_actual_cost` を作成します。\n\nこれを行うために使用する必要がある関数の1つが `math.ceil()` です。下のコードセルでこの関数の使用法を示します。数値を入力として受け取り、最も近い整数に切り上げます。\n\n次のコードセルを実行して、自分自身でこの関数をテストしてください。遠慮なく `test_value` の値を変更し、`math.ceil()` が期待する数値を返すことを確認してください。",

    "Use the next code cell to define the function `get_actual_cost()`.  You'll need to use the `math.ceil()` function to do this.\n\nWhen answering this question, note that it's completely valid to define a function that makes use of another function.  For instance, we can define a function `round_up_and_divide_by_three` that makes use of the `math.ceil` function:\n```\ndef round_up_and_divide_by_three(num):\n    new_value = math.ceil(num)\n    final_value = new_value / 3\n    return final_value\n```":
    "次のコードセルを使用して関数 `get_actual_cost()` を定義してください。これを行うには `math.ceil()` 関数を使用する必要があります。\n\nこの問題に答える際、ある関数内で他の関数を使用することは完全に有効であることに注意してください。たとえば、`math.ceil` 関数を利用する `round_up_and_divide_by_three` という関数を定義することができます：\n```python\ndef round_up_and_divide_by_three(num):\n    new_value = math.ceil(num)\n    final_value = new_value / 3\n    return final_value\n```",

    "Once your function is verified as correct, run the next code cell to calculate the updated cost of your project.":
    "関数が正解だと検証されたら、次のコードセルを実行してプロジェクトの更新されたコストを計算してください。",

    "Say you're working with a slightly larger room.  Run the next code cell to calculate the cost of the project.":
    "少し大きな部屋で作業しているとしましょう。次のコードセルを実行してプロジェクトのコストを計算してください。",

    "# Keep going\n\nContinue to learn about **[data types](https://www.kaggle.com/alexisbcook/data-types)**.":
    "# 次に進む\n\n続いて **[データ型（data types）](https://www.kaggle.com/alexisbcook/data-types)** について学びましょう。",

    "---\n\n\n\n\n*Have questions or comments? Visit the [course discussion forum](https://www.kaggle.com/learn/intro-to-programming/discussion) to chat with other learners.*":
    "---\n\n*質問やコメントがありますか？[コース ディスカッション フォーラム](https://www.kaggle.com/learn/intro-to-programming/discussion)を訪問して、他の学習者とチャットをしてみましょう。*"

}

def translate_notebook(path, translations):
    with open(path, "r", encoding="utf-8") as f:
        nb = json.load(f)

    for cell in nb["cells"]:
        if cell["cell_type"] == "markdown":
            src = "".join(cell["source"])
            if src in translations:
                cell["source"] = [translations[src]]
            # Fallback check if it has minor discrepancies like trailing spaces
            else:
                for k, v in translations.items():
                    if k.strip() == src.strip():
                        cell["source"] = [v]
                        break

    with open(path, "w", encoding="utf-8") as f:
        json.dump(nb, f, ensure_ascii=False, separators=(',', ':'))

translate_notebook(path_func, translations_func)
translate_notebook(path_ex, translations_ex)

print("Markdown translation completed successfully.")
